In [6]:
!pip install mnist

In [10]:
from PIL import Image
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
import mnist

In [11]:
# Train data:

x_train = mnist.train_images()
y_train = mnist.train_labels()

In [12]:
# Test data:

x_test = mnist.test_images()
y_test = mnist.test_labels()

In [14]:
print('X_train:\n', x_train)
print('X_test:\n', x_test)

X_train:
 [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
X_test:
 [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 

In [15]:
print('y_train:\n', y_train)
print('y_test:\n', y_test)

y_train:
 [5 0 4 ... 5 6 8]
y_test:
 [7 2 1 ... 4 5 6]


In [16]:
# How many dimensions does x_train has?

print(x_train.ndim)

3


In [17]:
# 60000 samples of 28x28 pixels:

print(x_train.shape)

(60000, 28, 28)


In [18]:
x_train = x_train.reshape((-1, 28*28))

In [19]:
# 60000 samples of 28x28 pixels but now they are in the same dimension:

print(x_train.shape)

(60000, 784)


In [20]:
# Let's do the same with x_test data:

x_test = x_test.reshape((-1, 28*28))

In [22]:
x_test.shape

(10000, 784)

In [24]:
# Checking one example of x_train:

print(x_train[0])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255
 247 127   0   0   0   0   0   0   0   0   0   0   0   0  30  36  94 154
 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0   0   0
   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82
  82  56  39   0   0   0   0   0   0   0   0   0   0   0   0  18 219 253
 253 253 253 253 198 182 247 241   0   0   0   0   

In [25]:
# Let's rescale it to 0 to 1:

x_train = (x_train/256)
x_test = (x_test/256)

In [26]:
# Checking it:

x_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [31]:
# Initilizing the model:

clf = MLPClassifier(solver='adam', activation='relu', hidden_layer_sizes=(64,64))

In [32]:
clf.fit(x_train, y_train)

MLPClassifier(hidden_layer_sizes=(64, 64))

In [33]:
# Testing the model with new predictions

predictions = clf.predict(x_test)

In [34]:
# Accuracy:

acc = confusion_matrix(y_test, predictions)

In [35]:
print(acc)

[[ 970    0    1    1    0    1    4    1    2    0]
 [   0 1127    2    2    0    1    2    0    1    0]
 [   0    1 1016    6    2    0    0    2    5    0]
 [   0    0    9  984    1    2    0    7    3    4]
 [   1    0    5    0  960    0    2    3    2    9]
 [   1    2    1   10    1  867    3    0    5    2]
 [   6    4    0    1    5    6  935    0    1    0]
 [   1    5    9    2    0    0    0 1004    1    6]
 [   1    1    3    9    3    5    3    5  939    5]
 [   1    4    0    4   12    4    0    2    3  979]]


In [36]:
# The accuracy is the sum of the diagonal numbers divided by 
# the sum of all the number in the matrix:

def accuracy(cm):
    diagonal = cm.trace()
    elements = cm.sum()
    return diagonal/elements

In [37]:
print(accuracy(acc))

0.9781
